name: nightly-main
on:
  schedule:
    - cron:  '42 5 * * *'

jobs:
  main:
    name: main
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - workflowName: tests11i3.yml
            branch: main
          - workflowName: tests11i4.yml
            branch: main
          - workflowName: tests12.yml
            branch: main
    steps:
      - name: Execute ${{ matrix.workflowName }} on ${{ matrix.branch }}
        run: |
          gh workflow run ${{ matrix.workflowName }} --ref ${{ matrix.branch }}
